version: '3.8'

services:
  php:
    image: php:8.3-fpm
    container_name: php-container
    volumes:
      - ./src:/var/www/html
    depends_on:
      - composer

  composer:
    image: composer:2.8.2
    container_name: composer-container
    command: ["sh", "-c", "cd /var/www/html/travel_laravel && composer install"]

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:8080"
      - "8123:8123"
    depends_on:
      - php

