version: '3.8'

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb-T
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin01
      MYSQL_DATABASE: travel
    volumes:
      - ./database/:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dev_network

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: laravel_php
    container_name: php-T
    volumes:
      - ./src/travel/:/var/www/travel
    working_dir: /var/www/pharmacy
    expose:
      - 9000
    depends_on:
      - mariadb
    networks:
      - dev_network

  nginx:
    image: nginx:alpine
    container_name: nginx-T
    volumes:
      - ./src/travel/:/var/www/travel
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "1234:1234"
    depends_on:
      - php
    networks:
      - dev_network

networks:
  dev_network: