version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: app-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin01
      MYSQL_DATABASE: travel
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - travel_network

  php:
    image: php:8.3-fpm
    container_name: php-container
    volumes:
      - ./src:/var/www/html
    depends_on:
      - composer
    networks:
      - travel_network

  composer:
    image: composer:2.8.2
    container_name: composer-container
    volumes:
      - ./src:/var/www/html
    command: ["sh", "-c", "cd /var/www/html/travellaravel && composer install"]
    networks:
      - travel_network

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8123:8123"
    depends_on:
      - php
    networks:
      - travel_network

networks:
  travel_network: